### PR TITLE
STOR-1020: Rebase `csi-node-driver-registrar` to v2.7.0 for OCP 4.13

### PR DESCRIPTION
**Pull request by mpatlasov**
Diff to upstream v2.7.0:
https://github.com/kubernetes-csi/node-driver-registrar/compare/v2.7.0...mpatlasov:rebase-2.7.0

Major changes between 2.5.1 (OCP 4.12) and 2.7.0:

Revert of #214, node-driver-registrar will create the path specified by --kubelet-registration-path (#247, @mauriciopoppe)

Full changelogs:

https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.7.0

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
I think `Add v2.0.1 changelog` should not be cherry-picked - it's not in upstream v2.7.0 tag. And it's not in `openshift/master` either.

**Comment by duanwei33** [comment]
Checked the CI results look good for sidecar rebase.

**Pull request merged**
